### ISSUE TITLE
Preferred Coffee Beans

### ISSUE THREAD

**Issue by masonjames** [norcross/ama#4]
Do you grind your own beans? What's your favorite locally-sourced?

**Comment by norcross** [comment]
I do grind my own, yes. Folks have sent me coffee from all over the country (and other countries, for that matter) so I have a collection of stuff I get to use. my wife doesn't like most of it, so we keep ground Dunkin at the house for the basics and the first pot of the day.

for local, I usually go Buddy Brew or Kawa. But I really like what Dark Matter (in Chicago) does, and I've never had a bad blend from them.
