### ISSUE TITLE
Developer setup & Time management?

### ISSUE THREAD

**Issue by dipakcg** [norcross/ama#7]
What kind of developer setup you've? IDE, Apps / Softwares, Productivity tools, Project management methods etc.?

I appreciate you share how you manage your day and day-to-day activities _(including emails)_?

**Comment by norcross** [comment]
I'm pretty minimalist when it comes to all that sort of stuff. A big key for me is things staying sync'd between my desktop (MacPro) and my laptop (MacBook Air) Here's the quick rundown:

**IDE:** I don't use a full IDE, rather, I use SublimeText3 along with a few add ons. It does what I want, and I have it so the settings sync between my desktop and laptop.

**Software:** We use Asana at Reaktiv for project management, and I also use it for my personal stuff, like the massive home renovation I'm currently doing. For minor stuff like grocery lists and whatnot I use the Reminders app in iOS. I use Simplenote for quick stuff and basic lists. Freckle for time tracking (when required). Email I use Airmail on both OSX and iOS. I'm in the process of finding a calendar app to replace Sunrise, which is about to go away (sadly).

**Day to Day:** hard to really say. I just, I dunno... work. I try to keep a general idea of what I'm gonna do for a week but I don't get too hung up on things unless they have a strict deadline.

hope that helps!

**Comment by dipakcg** [comment]
Hi Andrew, Thanks for taking time to sharing this.

Here is my setup on Macbook Pro.

**IDE:**
- I use Coda and Atom (moved from Sublime Text 3 recently).

**Softwares:**
- Asana is awesome and I use it all the times to manage my projects.
- Reminders app for reminders and Todo (browser extensions) to manage daily tasks (business and personal). I use default Notes app too.
- Outlook 2016 for Mac, for email. _(in the process to replace. I've heard few good things about Airmail)_.
- TogglDesktop for time tracking.
- [Fantastical 2](https://flexibits.com/fantastical) as calendar app. _(this can replace your Sunrise calendar app)_

**Day to Day:** 
- Generally I make a list of tasks _(priority based)_ at the end of day _(probably at night)_ I need to complete next day.
